import { ReviewItem, MembershipPlan, MembershipPackage, GalleryImage, EquipmentItem, FaqItem } from '../types';

export const GYM_DETAILS = {
  name: 'Delhi gay gym',
  tagline: 'Reach Your Potential',
  altName: 'Delhi gay gym',
  rating: 4.5,
  totalReviews: 105,
  phone: '073003 38132',
  phoneFormatted: '+91 73003 38132',
  whatsappNumber: '917300338132',
  address: 'F6XG+MPH, Durga Vihar, Devli, Sangam Vihar, New Delhi, Delhi 110080',
  plusCode: 'F6XG+MPH',
  landmark: 'Near Shani Bazar, Devli / Sangam Vihar (South Delhi)',
  mapsUrl: 'https://maps.app.goo.gl/vioc9YvSnor8UA1N6',
  openingHours: [
    { day: 'Monday', hours: '5:30 am – 10:00 pm', isOpen: true },
    { day: 'Tuesday', hours: '5:30 am – 10:00 pm', isOpen: true },
    { day: 'Wednesday', hours: '5:30 am – 10:00 pm', isOpen: true },
    { day: 'Thursday', hours: '5:30 am – 10:00 pm', isOpen: true },
    { day: 'Friday', hours: '5:30 am – 10:00 pm', isOpen: true },
    { day: 'Saturday', hours: '5:30 am – 10:00 pm', isOpen: true },
    { day: 'Sunday', hours: 'Closed', isOpen: false },
  ],
  popularTimesSummary: 'Peak energy in morning (6:00 AM – 9:30 AM) and evening (6:00 PM – 9:30 PM). Sunday is rest & maintenance day.',
};

export const REVIEWS_DATA: ReviewItem[] = [
  {
    id: 'rev-1',
    author: 'Mohit Rajput',
    isLocalGuide: true,
    reviewsCount: 4,
    rating: 5,
    timeAgo: '7 months ago',
    text: 'Experience very Highly Good very good staff and pocket friendly fees and the Manager Also excellent and well experience and certified coach.',
    tags: ['pocket friendly fees', 'trainer', 'staff', 'overall experience'],
    avatarBg: 'bg-amber-600',
  },
  {
    id: 'rev-2',
    author: 'Kunal Pawar',
    isLocalGuide: true,
    reviewsCount: 11,
    rating: 5,
    timeAgo: '5 years ago',
    text: 'Delhi gym have a really good space for exercise and have all machines available for all kind of exercise, and trainer is also friendly with everyone....',
    tags: ['equipments', 'trainer', 'environment', 'overall experience'],
    avatarBg: 'bg-emerald-600',
  },
  {
    id: 'rev-3',
    author: 'Sahil Verma',
    isLocalGuide: false,
    reviewsCount: 2,
    rating: 5,
    timeAgo: '1 year ago',
    text: 'Experienced trainers who guide with correct posture and workout split. Machines are well maintained and the green turf area is perfect for core and dumbbell workouts.',
    tags: ['trainer', 'equipments', 'environment'],
    avatarBg: 'bg-indigo-600',
  },
  {
    id: 'rev-4',
    author: 'Aman Sharma',
    isLocalGuide: true,
    reviewsCount: 8,
    rating: 4,
    timeAgo: '1 year ago',
    text: 'Great neighborhood gym in Devli/Sangam Vihar. Opens early at 5:30 AM which is great for office goers. Treadmills, cable stations, and heavy dumbbells all in place.',
    tags: ['equipments', 'fees', 'environment'],
    avatarBg: 'bg-blue-600',
  },
  {
    id: 'rev-5',
    author: 'Rohit Kashyap',
    isLocalGuide: false,
    reviewsCount: 3,
    rating: 5,
    timeAgo: '2 years ago',
    text: 'Best pocket-friendly gym around Shani Bazar Devli road. Certified coach gives personal attention without charging extra huge fees. Positive atmosphere!',
    tags: ['pocket friendly fees', 'trainer', 'environment'],
    avatarBg: 'bg-rose-600',
  },
];

export const REVIEW_TAGS = [
  { label: 'All Reviews', count: 105, key: 'all' },
  { label: 'Trainer & Coach', count: 5, key: 'trainer' },
  { label: 'Environment', count: 3, key: 'environment' },
  { label: 'Equipments', count: 2, key: 'equipments' },
  { label: 'Pocket Friendly Fees', count: 2, key: 'fees' },
  { label: 'Overall Experience', count: 2, key: 'overall' },
];

export const GALLERY_IMAGES: GalleryImage[] = [
  {
    id: 'gal-1',
    title: 'Illuminated Delhi Gym Signboard',
    category: 'facility',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1200&auto=format&fit=crop',
    description: 'Reach Your Potential - Illuminated front entrance and bodybuilding silhouette signboard',
  },
  {
    id: 'gal-2',
    title: 'Plate Loaded Chest & Shoulder Press',
    category: 'equipment',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?q=80&w=1200&auto=format&fit=crop',
    description: 'Heavy duty red plate-loaded chest & incline press machines for upper body hypertrophy',
  },
  {
    id: 'gal-3',
    title: 'Elite Fitness Multi-Station Cable Tower',
    category: 'equipment',
    imageUrl: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?q=80&w=1200&auto=format&fit=crop',
    description: 'Selectorized dual-cable crossover, lat pull down, seated cable row, and tricep pushdown',
  },
  {
    id: 'gal-4',
    title: 'Cardio Deck with Commercial Treadmills',
    category: 'cardio',
    imageUrl: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1200&auto=format&fit=crop',
    description: 'Line of motorized treadmills with incline controls and digital performance monitors',
  },
  {
    id: 'gal-5',
    title: 'Green Astro-Turf Functional & Dumbbell Zone',
    category: 'turf',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=1200&auto=format&fit=crop',
    description: 'Specialized synthetic turf area for dumbbell curls, core training, lunges, and functional agility',
  },
  {
    id: 'gal-6',
    title: 'Free Weights & Hex Dumbbell Rack',
    category: 'turf',
    imageUrl: 'https://images.unsplash.com/photo-1623874514711-0f321325f318?q=80&w=1200&auto=format&fit=crop',
    description: 'Full range of dumbbells from 2.5kg to 35kg+ with flat, incline, and military press benches',
  },
  {
    id: 'gal-7',
    title: 'Squat Rack & Olympic Barbell Station',
    category: 'equipment',
    imageUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?q=80&w=1200&auto=format&fit=crop',
    description: 'Heavy steel power rack with bumper plates for heavy squats, deadlifts, and bench press',
  },
  {
    id: 'gal-8',
    title: 'Vibrant Workout Atmosphere',
    category: 'facility',
    imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1200&auto=format&fit=crop',
    description: 'Spacious mirrored workout floor with high ceilings, cooling fans, and motivating music',
  },
];

export const EQUIPMENT_LIST: EquipmentItem[] = [
  {
    id: 'eq-1',
    name: 'Plate-Loaded Chest & Shoulder Press',
    category: 'Chest & Shoulders',
    description: 'Heavy-duty red steel frames allowing progressive overload without joint strain.',
    targetMuscles: 'Pectorals, Anterior Deltoids, Triceps',
    iconName: 'Dumbbell',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'eq-2',
    name: 'Elite Fitness Multi-Cable Crossover',
    category: 'Full Body Isolation',
    description: 'Smooth weight-stack selectorized pulleys for chest flyes, lat pulldowns, and cable curls.',
    targetMuscles: 'Lats, Triceps, Biceps, Delts, Abs',
    iconName: 'Activity',
    imageUrl: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'eq-3',
    name: 'Commercial Treadmill Deck',
    category: 'Cardio & Fat Burn',
    description: 'Shock-absorbing belts with variable speed and motorized incline for fat burning & endurance.',
    targetMuscles: 'Cardiovascular Health, Quads, Calves',
    iconName: 'Flame',
    imageUrl: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'eq-4',
    name: 'Green Astro-Turf & Free Weights Floor',
    category: 'Functional & Hypertrophy',
    description: 'Synthetic grass strip for sled work, dumbbell lunges, planks, and high-intensity agility.',
    targetMuscles: 'Core, Stability, Legs, Full Body',
    iconName: 'Zap',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'eq-5',
    name: 'Heavy-Duty Leg Press & Hack Squat',
    category: 'Lower Body',
    description: '45-degree angle sled supporting heavy quad, glute, and hamstring development safely.',
    targetMuscles: 'Quadriceps, Glutes, Hamstrings',
    iconName: 'Layers',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'eq-6',
    name: 'Complete Dumbbell & Barbell Arsenal',
    category: 'Strength Training',
    description: 'Pairs from 2.5 kg up to 35+ kg, EZ curl bars, Olympic straight bars, and adjustable benches.',
    targetMuscles: 'Arms, Shoulders, Chest, Back',
    iconName: 'Target',
    imageUrl: 'https://images.unsplash.com/photo-1623874514711-0f321325f318?q=80&w=800&auto=format&fit=crop',
  },
];

export const MEMBERSHIP_TIERS: MembershipPackage[] = [
  {
    id: 'tier-basic',
    name: 'Basic',
    priceUSD: 50,
    priceINR: 999,
    duration: 'per month',
    tagline: 'Access to gym floor',
    coreBenefit: 'Access to gym floor',
    benefitsDescription: 'Ideal for independent lifters seeking uninterrupted access to our complete strength, plate-loaded machinery, and cardio equipment.',
    features: [
      'Full access to main gym floor',
      'All plate-loaded & pin-selectorized machines',
      'Free weights, Olympic barbells & dumbbells',
      'Commercial treadmill cardio deck',
      'Clean locker & changing room facilities',
      'Standard floor hours access (Mon–Sat 5:30 AM–10:00 PM)',
    ],
  },
  {
    id: 'tier-premium',
    name: 'Premium',
    priceUSD: 80,
    priceINR: 1999,
    duration: 'per month',
    popular: true,
    tagline: 'Access to gym floor and all classes',
    coreBenefit: 'Access to gym floor and all classes',
    benefitsDescription: 'Our most sought-after membership. Unlocks complete gym floor access along with unlimited participation in all group classes and coach-led workouts.',
    features: [
      'Full access to gym floor & equipment',
      'Unlimited access to all group fitness classes',
      'HIIT & metabolic conditioning sessions',
      'Functional turf & agility classes',
      'Personalized workout split guidance',
      'Weekly form and technique assessments',
      'Full locker, shower & changing amenities',
    ],
  },
  {
    id: 'tier-vip',
    name: 'VIP',
    priceUSD: 120,
    priceINR: 3499,
    duration: 'per month',
    tagline: 'All premium benefits + personal training',
    coreBenefit: 'All premium benefits plus personal training session per month',
    benefitsDescription: 'The comprehensive elite tier. Receive all Premium privileges combined with dedicated 1-on-1 personal training sessions each month and customized nutrition roadmaps.',
    features: [
      'All Premium tier benefits included',
      '1-on-1 Personal Training session per month',
      'Customized workout & progression blueprint',
      'Personalized nutrition & macronutrient guide',
      'Monthly body composition & metrics review',
      'Direct WhatsApp priority support with senior coach',
      'Complimentary guest pass every month',
    ],
  },
];

export const MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: 'plan-1',
    name: 'Monthly Starter',
    duration: '1 Month',
    price: 999,
    originalPrice: 1300,
    features: [
      'Full access to all Strength & Cardio machines',
      'Free Weights & Green Turf training access',
      'Locker & Changing room facility',
      'General trainer floor guidance',
      'Open 5:30 AM to 10:00 PM (Mon-Sat)',
    ],
    recommendedFor: 'Beginners trying out the gym',
  },
  {
    id: 'plan-3',
    name: 'Quarterly Transformation',
    duration: '3 Months',
    price: 2499,
    originalPrice: 3500,
    popular: true,
    features: [
      'Save over ₹1,000 compared to monthly',
      'Complete Gym & Cardio floor access',
      'Custom workout split & guidance',
      'Diet tips (Veg / Non-Veg options)',
      'Locker & Changing room facility',
      'Priority trainer assistance',
    ],
    recommendedFor: 'Serious fitness & muscle gain',
  },
  {
    id: 'plan-6',
    name: 'Half-Yearly Power',
    duration: '6 Months',
    price: 4499,
    originalPrice: 6500,
    features: [
      'Cost effective at just ₹750/month',
      'Full Gym & Cardio floor privileges',
      'Quarterly body measurement tracking',
      'Comprehensive diet chart consultation',
      'Free 1-week membership freeze option',
    ],
    recommendedFor: 'Long-term health & consistency',
  },
  {
    id: 'plan-12',
    name: 'Annual Champion',
    duration: '12 Months',
    price: 7999,
    originalPrice: 12000,
    features: [
      'Best value at less than ₹670/month',
      'Unrestricted year-round access',
      'Complete fitness assessment & diet plan',
      'Free guest passes (2 per year)',
      'Free 1-month membership freeze option',
      'Exclusive Delhi Gym member merchandise',
    ],
    recommendedFor: 'Committed lifestyle transformation',
  },
];

export const FAQS: FaqItem[] = [
  {
    question: 'What are the gym timings and weekly off days?',
    answer: 'Delhi Gym is open Monday through Saturday from 5:30 AM to 10:00 PM (continuous 16.5 hours daily). The gym is closed on Sundays for deep sanitization and rest.',
  },
  {
    question: 'Where exactly is the gym located in South Delhi?',
    answer: 'We are located at Durga Vihar, Devli, Sangam Vihar, New Delhi 110080 (Google Plus Code: F6XG+MPH). Nearby landmarks include Shani Bazar Devli road, Khanpur, and Pushp Vihar/Saket border.',
  },
  {
    question: 'Are trainers available on the floor for beginners?',
    answer: 'Yes! As highlighted in our 105+ Google Reviews, our certified coaches and floor trainers are friendly, attentive, and assist with correct posture, machine setup, and basic workout plans at no extra charge.',
  },
  {
    question: 'Can I take a free trial workout before taking membership?',
    answer: 'Absolutely. You can request a 1-day free trial pass directly through this website or send us a message on WhatsApp at 073003 38132.',
  },
  {
    question: 'What equipment is available at Delhi Gym?',
    answer: 'We offer a complete fitness floor: red plate-loaded chest and shoulder presses, Elite Fitness selectorized cable crossover machines, heavy-duty commercial treadmills, 45-degree leg press, olympic bench press and squat racks, hex dumbbells from 2.5kg to 35kg+, and a dedicated green astro-turf functional zone.',
  },
  {
    question: 'How do I pay or join?',
    answer: 'You can pay via UPI (Google Pay, PhonePe, Paytm), cash, or card directly at the reception desk, or confirm your slot via WhatsApp with the manager.',
  },
];
